#--------------------------------------------------------------------------------------------------
# Google App Engine Server: rest-api-v1
# service.yaml
#
# This file determines how the Google App Engine service should be started, in what environment
# and runtime it should be used, the scaling and other options that are applicable to the Google
# App Engine environment.
#--------------------------------------------------------------------------------------------------
service: rest-api-v1
#--------------------------------------------------------------------------------------------------
# Configuration that specifies how the service should be started and in what environment
#--------------------------------------------------------------------------------------------------
runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT main:app
#--------------------------------------------------------------------------------------------------
# Configuration for the performance of the application. We chose 'basic_scaling' so we can decide
# the maximum number of instances and the idle_timeout. The idle_timeout specifies when a service
# should be closed after the last request. By default, this is 5minutes, but that seems a little
# soon.
#--------------------------------------------------------------------------------------------------
instance_class: B1
basic_scaling:
  max_instances: 2
  idle_timeout: 15m
#--------------------------------------------------------------------------------------------------
